name: Build updated Devkit image

on:
  workflow_dispatch: 
  schedule:
    - cron: "0 0 * * *"

env:
  IMAGE_PATH: ghcr.io/irneracoonovich/devkita64

permissions: 
  packages: write

jobs:
  Build_Image:
    name: Build updated Devkit image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Export image tag
        run: |
          echo "TAG=`date +%Y%m%d`" >> $GITHUB_ENV

      - name: Build image using Dockerfile
        run: |
          docker build . --pull -t $IMAGE_PATH
          docker tag $IMAGE_PATH $IMAGE_PATH:$TAG

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish image
        run: |
          docker push --all-tags $IMAGE_PATH
